cache:
    paths:
        - env2
        - env3

test2:
    script:
        - virtualenv env2 --system-site-packages && source env2/bin/activate
        - pip install pytest
        - cd containers && pip install -e .
        - cd ..
        - py.test containers/test

test3:
    script:
        - virtualenv env3 -P 3 --system-site-packages && source env2/bin/activate
        - pip install pytest
        - cd containers && pip install -e .
        - cd ..
        - py.test containers/test
